source 'https://cdn.cocoapods.org'
# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'PZKMPSwift' do
  # Keep framework-style imports while using static linkage for better startup performance.
  use_frameworks! :linkage => :static

  pod 'PZKMPBasic', :path => '/Users/zhoupengzu/Desktop/PZKMP/MyApplication/iosApp/PZKMPBasic'
  pod 'PZKMPHome', :path => '/Users/zhoupengzu/Desktop/PZKMP/MyApplication/iosApp/PZKMPHome'
  pod 'PZKMPThird', :path => '/Users/zhoupengzu/Desktop/PZKMP/MyApplication/iosApp/PZKMPThird'

  # Compose Multiplatform pod
  pod 'composeApp', :path => '../../composeApp'

end

post_install do |installer|
  # Xcode script sandbox blocks CocoaPods resource scripts from writing temp files in Pods/.
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
    end
  end

  installer.aggregate_targets.each do |aggregate_target|
    aggregate_target.user_project.native_targets.each do |target|
      next unless target.name == 'PZKMPSwift'

      target.build_configurations.each do |config|
        config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
      end
    end
    aggregate_target.user_project.save
  end
end
